# Generated by Django 3.0.8 on 2020-08-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('blood_type', models.CharField(max_length=100)),
                ('donation_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('city', models.CharField(max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='static/images')),
                ('blood_type', models.CharField(max_length=100)),
                ('hospital', models.CharField(max_length=100)),
                ('need', models.CharField(max_length=100)),
            ],
        ),
    ]
